#!/usr/bin/env bash
# all-modules -- List all modules
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2010-07-24
set -eu

# Directories having .module.install are considered as BuildKit modules.
# However, we should take care not to take over modules of nested source trees
# using BuildKit.
find * -name .module.install -print \
    -o -type d \( -name .git -o -execdir [ -d {}/buildkit ] \; \) -prune -false \
    2>/dev/null |
sed 's:/\.module\.install$::'
