#!/usr/bin/env bash
# build-modules -- Build given modules
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2010-07-25
set -eu
unset CDPATH

TimestampFmt=$1; shift

for Module; do
    timestamp=`printf "$TimestampFmt" "$Module"`
    echo "cd $Module && ./.module.build"
    if ! (
        cd "$Module"
        ./.module.build # TODO pass argument? e.g. build or clean
        ); then
        exit 1
    fi
    mkdir -p "`dirname "$timestamp"`"
    touch "$timestamp"
done
