#!/usr/bin/env bash
# build-modules -- Build given modules
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2010-07-25
set -eu

TimestampFmt=$1; shift

set +e
for Module; do
    timestamp=`printf "$TimestampFmt" "$Module"`
    if  (
        set -e
        echo "cd $Module && ./.module.build"
        cd "$Module"
        "./.module.build" # TODO pass argument? e.g. build or clean
        )
    then
        mkdir -p "`dirname "$timestamp"`"
        touch "$timestamp"
    fi
done
