#!/usr/bin/env bash
# check-build-depends -- Check build dependencies
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-05-28
set -eu

depends=${1:-$PWD/.depends}

generate-depends-checker "$depends" "### BuildKit: " |
DEPENDSDIR=$depends  bash -eu
