#!/usr/bin/env bash
# generate-staging-rules -- Generate make rules for staging each module
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2010-07-24
set -eu
unset CDPATH
set -o braceexpand
shopt -s extglob

echo '# Make rules for staging products of every module'
echo -n '# Generated: '; date +%FT%T%:z
echo

dstdirs=()
varsrcpatts=()

: >"$BUILDDIR"/stage.contents
for Module; do
    echo "# $Module"
    # define module variables for use in destination pathnames
    MODULE_PATH=$Module
    MODULE_NAME=${Module##*/}
    while read line; do
        # discard comments and empty lines
        line=${line%%#*}
        # XXX whitespace in .module.install is disallowed because of these two lines
        line=${line//[	 ]/ }
        read srcpatt dstpatt rest <<<"$line" || continue
        [ -n "$srcpatt" -a -n "$dstpatt" ] || continue
        numSrcs=0
        lastSrc=
        # expand source pathname
        eval set -- "$Module"/$srcpatt
        for src in "$@"; do
            let ++numSrcs
            lastSrc=$src
            src=${src#"$Module"/}
            dst=$dstpatt
            srcname=${src%/}
            # expand destination pathname
            case $dst in
                */)
                    dst+=${srcname##*/}
                    ;;
            esac
            dst=`eval echo "$dst"`
            # TODO normalize path systematically
            dstdir="\$(STAGEDIR)/${dst%/*}/"
            dst=${dst#./}
            dstdir=${dstdir//\/.\///}
            dstpath=$dst
            # make explicit whether source is a directory or not in its name
            if [ -d "$Module/$src" ]; then
                src=${src%/}/
                dstpath+=/
            fi
            # generate staging rule
            echo "\$(STAGED): \$(STAGEDIR)/$dst"
            echo "\$(STAGEDIR)/$dst: $Module/$srcname $dstdir"
            case $src in
                */) # a directory
                    # TODO is it better if we make rules for individual files under $src/?
                    echo "	mkdir -p \$@"
                    echo "	cp -rf \$</. \$@/"
                    echo "# XXX always copying since Make doesn't know if files are changed inside a directory or not"
                    echo ".PHONY: \$(STAGEDIR)/$dst"
                    ;;
                *) # a file
                    echo "	cp -f \$< \$@"
                    ;;
            esac
            # record in stage contents
            echo "./$dstpath" >>"$BUILDDIR"/stage.contents
            # remember destination directory for later
            dstdirs+=("$dstdir")
        done
        # skip if only a single rule was generated, or
        [ $numSrcs -eq 1 -a x"$lastSrc" = x"$Module/$srcpatt" ] ||
        # if no glob or extglob pattern, or
        [ x"${srcpatt//[?*[\]]/}" = x"$srcpatt" -a x"${srcpatt//[?*+@!]\(/}" = x"$srcpatt" ] ||
        # remember this is a variable src pattern to show a warning later
        varsrcpatts+=("$Module/$srcpatt")
    done <"$Module"/.module.install 
    echo
done

# generate directory creation rules
if [ ${#dstdirs[@]} -gt 0 ]; then
    echo "# Directories"
    printf '%s\n' "${dstdirs[@]}" | awk '!a[$0]++ {print}' |
    while read dstdir; do
        dstpath=".${dstdir#\$(STAGEDIR)}"
        if grep -qxF "$dstpath" <"$BUILDDIR"/stage.contents; then
            echo "#$dstdir: # custom rule creation exists"
        else
            echo "$dstdir:"
            echo "	mkdir -p \$@"
        fi
    done
fi

# generate stage contents list
(
cd "$BUILDDIR"
# augment the list with closure of parent directories
xargs -L1 dirname <stage.contents | sort -u >parents
dirnames() {
    {
        cat parents
        xargs -L1 dirname <parents
    } | sort -u >parents0
    if ! diff -q parents parents0 >/dev/null; then
        mv -f parents0 parents
        dirnames
    else
        rm -f parents0
    fi
}
dirnames
sort parents stage.contents >stage.contents.sorted
mv -f stage.contents.sorted stage.contents
rm -f parents
sed -n '\:/$: s:/$:\\(/.*\\)\\?$:p' <stage.contents >stage.contents.dirs
)

# generate what's to be done after staging
echo '$(STAGED):'
echo '	@STAGEDIR=$(STAGEDIR) BUILDDIR=$(BUILDDIR) \'
echo "remove-stale-files"
echo '#	@touch $@'
echo '	### BuildKit: staged all modules'
# XXX warning about variable source patterns in .module.install files
if [ ${#varsrcpatts[@]} -gt 0 ]; then
    echo '	@echo >&2'
    echo '	@echo "### BuildKit: WARNING! Run \`make index\` after adding/removing following files:" >&2'
    for varsrcpatt in "${varsrcpatts[@]}"; do
        echo '	@echo "###   '"$varsrcpatt"'" >&2'
    done
fi
