#!/usr/bin/env bash
# generate-build-rules -- Generate make rules for building each module
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-04-08
set -eu
unset CDPATH
set -o braceexpand
shopt -s extglob

echo '# Make rules for building every module'
echo -n '# Generated: '; date +%FT%T%:z
echo

prefixBuilt=timestamp/
suffixBuilt=.built
prefixModified=timestamp/
suffixModified=.lastmodified

for Module; do
    echo "# $Module"
    MODULE_PATH=$Module
    MODULE_NAME=${Module##*/}
    if [ -x "$Module"/.module.build ]; then
        echo "build: \$(BUILDDIR)/$prefixBuilt$Module$suffixBuilt"
        # dependencies
        if [ -e "$Module"/.module.depends ]; then
            sed 's/[[:space:]]*#.*//' <"$Module"/.module.depends | grep -v '^$' |
            while read -r dep; do
                echo "#  $Module depends on $dep"
                echo "\$(BUILDDIR)/$prefixBuilt$Module$suffixBuilt: \$(BUILDDIR)/$prefixBuilt$dep$suffixBuilt"
            done
        fi
        # build rule
        echo "\$(BUILDDIR)/$prefixBuilt$Module$suffixBuilt: \$(BUILDDIR)/$prefixModified$Module$suffixModified \$(DEPENDS)"
        ModuleEscaped=$(sh-escape "$Module")
        echo "	cd $ModuleEscaped && ./.module.build $ModuleEscaped"
        echo "	@mkdir -p '\$(@D)' && touch '\$@'"
    else
        echo '#  (no executable .module.build)'
    fi
    echo
done
echo "\$(BUILDDIR)/$prefixModified%$suffixModified:"
echo "	@BUILDDIR=\$(BUILDDIR) create-modules-lastmodified '\$*'"
