#!/usr/bin/env bash
# generate-staging-rules -- Generate make rules for staging each module
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2010-07-24
set -eu
unset CDPATH
set -o braceexpand
shopt -s extglob

# commands for copying each file and directory to the stage
stageFile() { echo "cp -f $1 $2"; }
stageDir()  { echo "rm -rf $2; \\"; echo "cp -Rfa $1 $2"; }

# use rsync for directory instead of cp -R when available
if type rsync &>/dev/null; then
    #stageFile() { echo "rsync $1 $2"; } # XXX using rsync for individual files is slower than cp
    stageDir() { echo "rsync -aH --delete $1 $2"; }
fi

echo '# Make rules for staging products of every module'
echo -n '# Generated: '; date +%FT%T%:z
echo

dstdirs=()
varsrcpatts=()


: >"$BUILDDIR"/stage.contents
for Module; do
    echo "# $Module"
    # define module variables for use in destination pathnames
    MODULE_PATH=$Module
    MODULE_NAME=${Module##*/}
    while read line; do
        # discard comments and empty lines
        line=${line%%#*}
        # XXX whitespace in .module.install is disallowed because of these two lines
        line=${line//[	 ]/ }
        read srcpatt dstpatt rest <<<"$line" || continue
        [[ -n "$srcpatt" && -n "$dstpatt" ]] || continue
        numSrcs=0
        lastSrc=
        # expand source pathname
        eval set -- "$Module"/$srcpatt
        for src in "$@"; do
            let ++numSrcs
            lastSrc=$src
            src=${src#"$Module"/}
            dst=$dstpatt
            # there are four cases of $src and $dst:
            #   foo   bar   # stages file     foo   to bar
            #   foo   bar/  # stages file/dir foo   to bar/foo
            #   foo/  bar   # stages      dir foo/. to bar/.
            #   foo/  bar/  # stages      dir foo/. to bar/foo/.
            # and some more with dots and stars:
            #   foo/. bar   # stages      dir foo/. to bar/.
            #   foo/. bar/  # stages      dir foo/. to bar/foo/.
            #   foo/* bar/  # stages files in foo/* to bar/*
            # normalize the source path
            src=${src%%+(/.)}                   # no /. suffix
            srcname=${src%%+(/)}                # the name without / suffix
            # first, expand destination path
            case $dst in */) dst+=${srcname##*/} ;; esac
            dst=`eval echo "$dst"`
            # normalize the path
            [[ $dst != /* ]] || dst=.$dst       # no absolute paths
            dst=${dst//@(+(\/)|\/.\/)//}        # no repeated slashes, or /./
            dst=${dst#./}                       # no ./ prefix
            dstdir="\$(STAGEDIR)/${dst%/*}/"
            dstpath=$dst
            # make explicit whether source is a directory or not in its name
            if [[ $src = */ || -d "$Module/$src" ]]; then
                src=$srcname/
                dstpath+=/
            fi
            # generate staging rule
            echo "\$(STAGED): \$(STAGEDIR)/$dst"
            echo "\$(STAGEDIR)/$dst: $Module/$srcname $dstdir"
            case $src in
                */) # a directory
                    # TODO is it better if we make rules for individual files under $src/?
                    echo "	mkdir -p \$@"
                    echo "	$(stageDir "\$</." "\$@/")"
                    echo "# XXX always copying since Make doesn't know if files are changed inside a directory or not"
                    echo ".PHONY: \$(STAGEDIR)/$dst"
                    ;;
                *) # a file
                    echo "	$(stageFile "\$<" "\$@")"
                    ;;
            esac
            # record in stage contents
            echo "./$dstpath" >>"$BUILDDIR"/stage.contents
            # remember destination directory for later
            dstdirs+=("$dstdir")
        done
        # skip if only a single rule was generated, or
        [ $numSrcs -eq 1 -a x"$lastSrc" = x"$Module/$srcpatt" ] ||
        # if no glob or extglob pattern, or
        [ x"${srcpatt//[?*[\]]/}" = x"$srcpatt" -a x"${srcpatt//[?*+@!]\(/}" = x"$srcpatt" ] ||
        # remember this is a variable src pattern to show a warning later
        varsrcpatts+=("$Module/$srcpatt")
    done <"$Module"/.module.install 
    echo
done

# generate directory creation rules
if [[ ${#dstdirs[@]} -gt 0 ]]; then
    echo "# Directories"
    printf '%s\n' "${dstdirs[@]}" | awk '!a[$0]++ {print}' |
    while read dstdir; do
        dstpath=".${dstdir#\$(STAGEDIR)}"
        if grep -qxF "$dstpath" <"$BUILDDIR"/stage.contents; then
            echo "#$dstdir: # custom rule creation exists"
        else
            echo "$dstdir:"
            echo "	mkdir -p \$@"
        fi
    done
fi

# generate stage contents list
(
cd "$BUILDDIR"
# augment the list with closure of parent directories
xargs -L1 dirname <stage.contents | sort -u >parents
dirnames() {
    {
        cat parents
        xargs -L1 dirname <parents
    } | sort -u >parents0
    if ! diff -q parents parents0 >/dev/null; then
        mv -f parents0 parents
        dirnames
    else
        rm -f parents0
    fi
}
dirnames
sort parents stage.contents >stage.contents.sorted
mv -f stage.contents.sorted stage.contents
rm -f parents
sed -n '\:/$: s:/$:\\(/.*\\)\\?$:p' <stage.contents >stage.contents.dirs
)

# generate what's to be done after staging
echo '$(STAGED):'
echo '	@! [ -e $(STAGEIGNORE) -a ! -L $(BUILDDIR)/stage.ignore ] || relsymlink $(STAGEIGNORE) $(BUILDDIR)/stage.ignore'
echo '	@STAGEDIR=$(STAGEDIR) BUILDDIR=$(BUILDDIR) \'
echo "remove-stale-files"
echo '#	@touch $@'
echo '	### BuildKit: staged all modules'
# XXX warning about variable source patterns in .module.install files
if [[ ${#varsrcpatts[@]} -gt 0 ]]; then
    echo '	@echo >&2'
    echo '	@echo "### BuildKit: WARNING! Run \`make refresh\` after adding/removing following files:" >&2'
    for varsrcpatt in "${varsrcpatts[@]}"; do
        echo '	@echo "###   '"$varsrcpatt"'" >&2'
    done
fi
