#!/bin/sh
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2010-07-25
# See: http://stackoverflow.com/questions/1668284/bash-script-to-find-the-most-recently-modified-file
find "$@" | xargs ls -dt 2>/dev/null
