#!/bin/sh
# package-os-x-app-dmg -- Generate a .dmg given an OS X App and template .dmg
# usage: package-os-x-app-dmg APPNAME TEMPLATEDMG
# 
# This tool will generate APPNAME.dmg by combining contents of APPNAME.app and
# those from TEMPLATEDMG.  The APPNAME.app to be injected should be in the
# current working directory, whereas TEMPLATEDMG can be any path reachable from
# it.  The APPNAME.dmg will be created in the current working directory, that
# is where you run this tool.
#
# See: http://digital-sushi.org/entry/how-to-create-a-disk-image-installer-for-apple-mac-os-x/
set -e

[ $# -eq 2 ] || { sed -n '2,/^#$/ s/^# //p'; exit 1; }
AppName=$1; shift
TemplateDMGPath=$1; shift

rm -f "$AppName".sparseimage
hdiutil convert "$TemplateDMGPath" -format UDSP -o "$AppName"
hdiutil mount "$AppName".sparseimage
cp -pPR "$AppName".app/Contents /Volumes/"$AppName"/"$AppName".app/Contents
hdiutil eject /Volumes/"$AppName"
rm -f "$AppName".dmg
hdiutil convert "$AppName".sparseimage -format UDBZ -o "$AppName".dmg
rm -f "$AppName".sparseimage
