#!/usr/bin/env bash
# Install symlinks to given files under DESTDIR of DEPENDS_PREFIX
# Usage: place-depends-symlinks DESTDIR FILE...
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-11-05
set -eu

DestDir=$1; shift

# make sure we have DESTDIR under DEPENDS_PREFIX
mkdir -p "$DEPENDS_PREFIX"/"$DestDir"

# place symlinks to $DEPENDS_PREFIX/$DESTDIR
for f; do
    [ -e "$f" ] || continue
    relsymlink "$f" "$DEPENDS_PREFIX"/"$DestDir"/
done
