#!/bin/sh -e
# pojang -- build an executable by packing given files and dirs
# Home: http://netj.org/2008/03/pojang
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2008-03-13
# 
# Usage:
#   pojang <entry-file> [<tar options>] <file>... > <executable>
# 
# Example:
#   # Suppose you have a nice `tool' consisting of multiple files.
#   # And, you use it through its `bin/shell', for example:
#   /path/to/tool/bin/shell command1 arg1 arg2 ...
# 
#   # But, it becomes a bit clumsy when you want to carry it around.
#   # This is where `pojang' plays its role.  Make the tool handy by:
#   cd /path/to/tool
#   pojang bin/shell bin/cmd-* lib/*.sh share/*.txt ... >~/tool
#   chmod +x ~/tool
# 
#   # Now, move/copy/share your favorite tool as you do with your files.
#   cp tool mytool-in-a-file
#   ./mytool-in-a-file
#   mv mytool-in-a-file .Trash/
#   scp tool somehost:bin/

# show usage
if [ $# -eq 0 ]; then
    sed -ne '/^# Usage:/,/^$/ s/^# //p' <"$0"
    exit 1
fi

# check entry
entry=$1
if ! [ -f "$entry" -a -x "$entry" ]; then
    echo "$entry is not an executable entry" >&2
    exit 2
fi

# begin with the pojang driver
basename=`basename "$PWD" || echo pojang`
drvlen=`sed -ne '/<<DRV$/,/^DRV/p' <"$0" | wc -l | tr -d " "`
cat <<DRV
#!/bin/sh -e
# an executable packed with pojang -- http://netj.org/2008/03/pojang
tmp=\`mktemp -d /tmp/$basename.XXXXXX\`
trap "rm -rf \$tmp" 0
tail -n +$drvlen "\$0" | gzip -d | (cd \$tmp; tar xpf -)
\$tmp/$entry "\$@"
exit \$?
DRV
echo "# end of pojang driver, package content follows"

# and the tar archive follows
tar cf - "$@" | gzip
