#!/usr/bin/perl
# relpath -- Compute relative path from one to the other
# Usage: relpath [BASEPATH] PATH...
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-04-09
# See: abs2rel from http://perldoc.perl.org/File/Spec.html#METHODS
# See: https://gist.github.com/SteveRyherd/5044132
#
# Switched to Perl because of Python < 2.6 not supporting relpath from os.path.

use strict;
use File::Spec;
use Cwd 'abs_path';

my $base;
if (@ARGV < 1) {
    print "Usage: relpath [BASEPATH] PATH...\n";
    exit 1;
} elsif (@ARGV > 1) {
    $base = shift @ARGV;
} else {
    $base = '';
}

my $base_abs = abs_path($base);
for my $p (@ARGV) {
    printf "%s\n", File::Spec->abs2rel(abs_path($p), $base_abs);
}
