#!/usr/bin/env bash
# remove-stale-files -- Remove stale files from stage
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2011-01-30
set -eu
unset CDPATH

# nothing to do without a stage :)
[ -d "$STAGEDIR" ] || exit 0

# find files in stage
ignore="$BUILDDIR"/stage.ignore
if [ -s "$ignore" ] && type git &>/dev/null; then
    # ignore some files with git
    (
    GIT_DIR="$BUILDDIR"/stage.ignore.git
    [ -d "$GIT_DIR" ] || git init --quiet --bare "$GIT_DIR"
    git --git-dir="$GIT_DIR" --work-tree="$STAGEDIR" ls-files \
        --full-name -z --others --directory --exclude-from="$ignore" . |
    tr '\0' '\n' |
    sed 's:^:./:' |
    sort
    )
else
    (
    cd "$STAGEDIR"
    find . | sort
    )
fi >"$BUILDDIR"/stage.found

# find files not specified in contents except dirs from them
(
cd "$BUILDDIR"
comm -13 stage.contents stage.found |
if ! [ -s stage.contents.dirs ]; then cat
else grep -vf stage.contents.dirs; fi || true
) >"$BUILDDIR"/stage.stale

# remove stale files from stage
(
cd "$STAGEDIR"
xargs rm -rfv | sed '
    /removed .*‘\./ s*removed .\*‘\.*removed stale file: ‘'"$STAGEDIR"'*
    \#^\./#                    s*^\.*removed stale file: '"$STAGEDIR"'*
'
) <"$BUILDDIR"/stage.stale
