#!/usr/bin/env bash
# Install symlinks to given files that satisfy TEST_PREDICATE under DESTDIR of $DEPENDS_PREFIX
# Usage: symlink-under-depends-prefix DESTDIR TEST_PREDICATE FILE...
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-11-05
set -eu

: ${DEPENDS_PREFIX:?This command is intended to be used only in scripts that work with check-depends of BuildKit}

DestDir=$1; shift
TestPredicate=$1; shift

# make sure we have DESTDIR under $DEPENDS_PREFIX
mkdir -p "$DEPENDS_PREFIX"/"$DestDir"

# place symlinks to $DEPENDS_PREFIX/DESTDIR
for f; do
    [ $TestPredicate "$f" ] || continue
    relsymlink "$f" "$DEPENDS_PREFIX"/"$DestDir"/
done
