#!/usr/bin/env bash
# @@SHELL_NAME@@-help -- Shows help
# > @@SHELL_NAME@@ help [COMMAND]
##
# Template-Author: Jaeho Shin <netj@cs.stanford.edu>
# Template-Created: 2015-07-30
# Generated: @@GENERATED_TIMESTAMP@@
set -eu

if [[ $# -gt 0 ]]; then
    Cmd=$1; shift
    exe=@@SHELL_NAME@@-"$Cmd"
    if exePath=$(type -p "$exe"); then
        exec usage "$exePath"
    else
        usage "$0" "$Cmd: invalid COMMAND" || true  # continue to enumerate available ones
    fi
else
    usage "$0"
fi

# enumerate available COMMANDs discoverable from PATH
echo
echo "# Available COMMANDs are:"
IFS=:
tmp=$(mktemp -d "${TMPDIR:-/tmp}"/@@SHELL_NAME@@-help.XXXXXXX)
trap 'rm -rf "$tmp"' EXIT
for path in $PATH; do
    for exe in "$path"/@@SHELL_NAME@@-*; do
        [ -x "$exe" ] || continue
        usage "$exe" | head -1 | sed -n '/ -- / s/.* -- //p' >>"$tmp"/desc
        cmd=${exe##*/@@SHELL_NAME@@-}
        echo "@@SHELL_NAME@@ $cmd  #"
    done
done | column -t >"$tmp"/commands
paste "$tmp"/commands "$tmp"/desc
