#!/usr/bin/env bash
# @@SHELL_NAME@@-version -- show @@SHELL_NAME@@'s version and build information
# > @@SHELL_NAME@@ version
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2014-10-09
# Generated: @@GENERATED_TIMESTAMP@@
set -eu

cd "$@@SHELL_ENVVARPREFIX@@_HOME"
. .build-info.sh

cat <<-HEADER
@@PROJECTNAME@@ $version ($build_os $build_machine)
HEADER

if [ -s LICENSE.txt ]; then
    echo
    sed 's/^/  /' <LICENSE.txt
    echo
fi

cat <<-VERSION
Information on this build of @@PROJECTNAME@@ follows.

  @@PROJECTNAME@@ version: $version_long
  @@PROJECTNAME@@ Git commit: $version_commit
  
  Build Date: $build_timestamp
  Build Host: $build_hostname
  Build Operating System: $build_os
  Build Machine: $build_machine
  
  Bundled Dependencies:
$(ls @@RUNTIMEDEPENDSDIR@@/bundled | sed 's/^/    /')

  Running Operating System: $(uname)
  Running Machine: $(uname -m)
  
VERSION
