#!/usr/bin/env bash
# @@SHELL_NAME@@-hack -- run commands inside @@SHELL_NAME@@'s environment
# > @@SHELL_NAME@@ hack [COMMAND [ARG]...]
##
# Template-Author: Jaeho Shin <netj@cs.stanford.edu>
# Template-Created: 2015-07-30
# Generated: @@GENERATED_TIMESTAMP@@
set -eu

[ $# -gt 0 ] || set -- bash --norc -i

exec "$@"
