#!/usr/bin/env bash
# @@SHELL_NAME@@-hack -- run commands inside @@SHELL_NAME@@'s environment
# > @@SHELL_NAME@@ hack [COMMAND [ARG]...]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-05-10
set -eu

[ $# -gt 0 ] || set -- bash --norc -i

exec "$@"
